# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: milaap.org
  database: auth_production
  pool: 5
  username: readonly
  password: strawberry-slurp-101@milaap
  socket: /var/lib/mysql/mysql.sock


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: milaap.org
  database: auth_production
  pool: 5
  username: readonly
  password: strawberry-slurp-101@milaap
  socket: /var/lib/mysql/mysql.sock

fundraiser_db:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: staging.milaap.org
  database: fundraiser_app_development
  pool: 5
  username: puneet
  password: puneet@milaap
  socket: /var/lib/mysql/mysql.sock